name: Manual Drift Detection
on:
  workflow_dispatch

jobs: 
  try:
    name: try
    runs-on: ubuntu-latest
  
    steps:
      - name: Get Job Run URL
        shell: bash
        run: |-
          for ((i=1;i<=100;i++));
          do 
            curl "https://api.github.com/users/geerlingguy/repos?per_page=100&page=$i" | jq -r '.[] | .name'
          done
